DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS chessboard;
DROP TABLE IF EXISTS history;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL
);

CREATE TABLE chessboard (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    boardpieces TEXT NOT NULL,
    playermove TEXT NOT NULL
);
CREATE TABLE history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    winner TEXT NOT NULL,
    loser TEXT NOT NULL,
    FOREIGN KEY (winner) REFERENCES user (id),
    FOREIGN KEY (loser) REFERENCES user (id)
);
