@hostname = http://127.0.0.1:5000/

put {{hostname}}/api/practiceboard/1
Content-Type: application/json

{
    "fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
}

###
get {{hostname}}/api/chessboard/1

###


get {{hostname}}/static/images/chessPieces/bB.png

###


put {{hostname}}/user/christian
Content-Type: application/json

{
    "elo": 1400
}


###
put {{hostname}}/user/bobby
Content-Type: application/json

{
    "pw": "bobby",
    "elo": 2000
}

###
get {{hostname}}/user/Christian


###
delete {{hostname}}/user/mark

###
patch {{hostname}}/user/bobby
Content-Type: application/json

{
    "username": "bobby",
    "elo": 3000
}


###
put {{hostname}}/video/1
Content-Type: application/json

{
    "likes": 10
}