@hostname = http://127.0.0.1:5000/
post {{hostname}}/api/chesspuzzle/
Content-Type: application/json

{
    "fen": "2pr1rk1/1p1bppp1/6p1/pP1npqPn/4N2P/P2PP3/1B2BP2/R2QK2R w KQkq - 1 0",
    "solution": "Nf6"
}

###
get {{hostname}}/api/chesspuzzle


###
put {{hostname}}/api/practiceboard/1
Content-Type: application/json

{
    "fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
}

###
get {{hostname}}/api/chessboard/1

###


get {{hostname}}/static/images/chessPieces/bB.png

###


put {{hostname}}/user/christian
Content-Type: application/json

{
    "elo": 1400
}


###
put {{hostname}}/user/bobby
Content-Type: application/json

{
    "pw": "bobby",
    "elo": 2000
}

###
get {{hostname}}/user/Christian


###
delete {{hostname}}/user/mark

###
patch {{hostname}}/user/bobby
Content-Type: application/json

{
    "username": "bobby",
    "elo": 3000
}


###
put {{hostname}}/video/1
Content-Type: application/json

{
    "likes": 10
}